### PR TITLE
Initialise compiler plugins before loading a target

### LINKED ISSUE #1264: Possible to use additional ghc-option "-fplugin=X"?
My current issue: I'm working on code that uses Polysemy, which uses a custom plugin to drive some type inference. This is usually enabled by adding `-fplugin=Polysemy.Plugin` to ghc-options section of cabal file; see https://github.com/isovector/polysemy/tree/master/polysemy-plugin. 

However, it looks like when HIE is running through my IDE (currently VSCode), it's not using this plugin `ghc-options` override so I see compile errors in my IDE even though there aren't any when compiling through command line. 

Is there a way to specify additional GHC options like this custom plugin when interfacing with HIE?

### PR DESCRIPTION
**Pull request by fendor**
This initialises plugins before loading the target.
closes [#1264](https://github.com/haskell/haskell-ide-engine/issues/1264)

What works: 
Example project at  [polysemy-hie-experiment](https://github.com/fendor/polysemy-hie-experiment)
Current behaviour: Compiler error, ambiguous types.
Expected behavior: compiles.

This works now if the flag `-fplugin=Polysemy.Plugin` is specified in the *.cabal file.
However, the option `{-# OPTIONS_GHC -fplugin=Polysemy.Plugin #-}` in the source file does not suffice currently.

### CODE REVIEW

**Comment by wz1000** [comment]
Did you try calling `initialise-plugins` after depanal?

**Comment by fendor** [comment]
Yes, no errors were shown but diagnostics did not work. E. G. No type information on hover nor obvious errors were shown

**Comment by wz1000** [comment]
Do you see anything when you enable `--vomit`?

**Comment by fendor** [comment]
No, didn't enable it, but I can try later.
Why? When should plugins be loaded?

**Comment by wz1000** [comment]
`--vomit` can give you more insight on what is going wrong in the second case.

**Comment by alanz** [comment]
@fendor can you target this at my `thinned-api` branch?  It should apply cleanly

**Comment by fendor** [comment]
Will do ASAP! Any more feedback to it, though?

**Comment by alanz** [comment]
Just looking at it I don't see anything troublesome, but I assume you have tested it and it actually solves th problem.

Ping @DanielG, you will need this for your new backend.

**Comment by fendor** [comment]
I tested it for my specific use-case, not in general. I dont know if this causes any unexpected side-effects.

**Comment by fendor** [comment]
So, close this in favour of #19?

**Comment by alanz** [comment]
yes

**Pull request closed without merging**
